name: Cloud-Sentry-Daily-Scan
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  id-token: write  
  contents: read   

jobs:
  audit-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Boto3
        run: pip install boto3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::462457676536:role/github 
          aws-region: us-east-1
      - name: Execute Sentinel
        env:
          PYTHONPATH: .
        run: python3 src/main.py
