name: Cloud-Sentry-Daily-Scan
on:
  schedule:
    - cron: '0 0 * * *' # Midnight daily
  workflow_dispatch: # Allows manual run button

jobs:
  audit-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Boto3
        run: pip install boto3
      - name: Execute Sentinel
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          PYTHONPATH: .
        run: python3 src/main.py