name: Cloud-Sentry-Daily-Scan
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:      # Allows you to click the 'Run workflow' button manually

permissions:
  id-token: write         # MANDATORY for secure OIDC authentication
  contents: read          # Required to checkout the code from your repo

jobs:
  audit-cloud:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Clears the deprecation warnings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Upgraded to meet 2026 Boto3 standards

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Future-proofed for 2026/2027 standards

      - name: Install Multi-Cloud Dependencies
        run: |
          pip install boto3 \
            google-cloud-storage \
            google-api-python-client \
            cloud-sql-python-connector \
            azure-mgmt-storage \
            azure-mgmt-sql \
            azure-mgmt-network \
            azure-identity

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Match the exact IAM role name 'github' from your screenshot
          role-to-assume: arn:aws:iam::462457676536:role/github 
          aws-region: us-east-1

      - name: Execute Sentinel
        env:
          PYTHONPATH: . # CRITICAL: Allows Python to find the 'src' directory
        run: python3 src/main.py
